# Generated by Django 4.0.5 on 2022-07-20 14:21

import ckeditor_uploader.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='portfolioproject',
            name='excerpt',
            field=ckeditor_uploader.fields.RichTextUploadingField(max_length=600, validators=[django.core.validators.MinLengthValidator(10)]),
        ),
    ]
